//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grid
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string first { get; set; }
        public string last { get; set; }
        public string gender { get; set; }
        public int age { get; set; }
    }
}
